;;; init.el --- Personal Emacs configuration -*- lexical-binding: t; -*-

;;; ============================================================
;;; PACKAGE ARCHIVES
;;; ============================================================
(setq package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("elpa"  . "https://elpa.gnu.org/packages/")))

;; Without this, use-package silently skips missing packages on a
;; fresh machine, which makes new installs confusingly broken.
(setq use-package-always-ensure t)

;;; ============================================================
;;; UNDO SYSTEM
;;; ============================================================
;; Linear vim-style undo for evil (alternative to Emacs's undo tree).
(use-package undo-fu)

;;; ============================================================
;;; EVIL — VIM EMULATION
;;; ============================================================
(use-package evil
  :demand t

  :init
  ;; These four MUST be set before evil loads — they're read once,
  ;; at package init time. Setting them in :config does nothing.
  (setq evil-want-keybinding nil)         ; let evil-collection handle other modes
  (setq evil-search-module 'evil-search)  ; vim-style search w/ persistent highlight
  (setq evil-want-minibuffer t)
  (setq evil-undo-system 'undo-fu)

  :config
  (setq evil-ex-search-persistent-highlight t)  ; :set hlsearch
  (setq evil-ex-search-incremental t)           ; :set incsearch
  (setq evil-ex-search-case 'smart)             ; smartcase

  (evil-mode 1)

  (evil-set-leader '(normal visual) (kbd "SPC"))

  (evil-define-key '(normal visual) 'global
    ;; Project (<leader>p)
    (kbd "<leader>pb") #'project-switch-to-buffer
    (kbd "<leader>pf") #'project-find-file
    (kbd "<leader>pp") #'project-switch-project
    (kbd "<leader>pg") #'project-find-regexp
    ;; Tools
    (kbd "<leader>g")  #'vc-dir
    (kbd "<leader>t")  #'vterm
    (kbd "<leader>r")  #'robot-run-test
    (kbd "<leader>n")  #'dired-jump)

  (define-key evil-normal-state-map (kbd "<escape>") #'evil-ex-nohighlight))

;;; ============================================================
;;; EVIL-COLLECTION — vim bindings for built-in modes
;;; ============================================================
(use-package evil-collection
  :after evil
  :config (evil-collection-init))

;;; ============================================================
;;; VC-DIR — minor evil-friendly tweaks
;;; ============================================================
;; vc-dir lands in evil normal state by default through evil-collection,
;; but v collides with evil's visual-state command, so rebind it here.
(with-eval-after-load 'vc-dir
  (evil-set-initial-state 'vc-dir-mode 'normal)
  (evil-define-key 'normal vc-dir-mode-map
    (kbd "v")   #'vc-next-action            ; commit / register+commit
    (kbd "TAB") #'vc-dir-next-directory))

;;; ============================================================
;;; EVIL-SURROUND — ys/cs/ds for quotes, parens, tags
;;; ============================================================
(use-package evil-surround
  :ensure t
  :after evil
  :config (global-evil-surround-mode 1))

;;; ============================================================
;;; CUSTOM-SET-VARIABLES — auto-generated by M-x customize
;;; ============================================================
(custom-set-variables
 '(custom-safe-themes
   '("13096a9a6e75c7330c1bc500f30a8f4407bd618431c94aeab55c9855731a95e1"
     "c9d837f562685309358d8dc7fccb371ed507c0ae19cf3c9ae67875db0c038632"
     "e622620e5f31216fd71e492fc1476e1fe7c21b8dc5811bf9e640c4b1fd6cfac1"
     "21d2bf8d4d1df4859ff94422b5e41f6f2eeff14dd12f01428fa3cb4cb50ea0fb"
     "8d3ef5ff6273f2a552152c7febc40eabca26bae05bd12bc85062e2dc224cde9a"
     "f1e8339b04aef8f145dd4782d03499d9d716fdc0361319411ac2efc603249326"
     "8c7e832be864674c220f9a9361c851917a93f921fedb7717b1b5ece47690c098"
     "93011fe35859772a6766df8a4be817add8bfe105246173206478a0706f88b33d"
     "e14289199861a5db890065fdc5f3d3c22c5bac607e0dbce7f35ce60e6b55fc52"
     "d12b1d9b0498280f60e5ec92e5ecec4b5db5370d05e787bc7cc49eae6fb07bc0"
     "dd4582661a1c6b865a33b89312c97a13a3885dc95992e2e5fc57456b4c545176"
     "aec7b55f2a13307a55517fdf08438863d694550565dee23181d2ebd973ebd6b8"
     "9e5e0ff3a81344c9b1e6bfc9b3dcf9b96d5ec6a60d8de6d4c762ee9e2121dfb2"
     "3613617b9953c22fe46ef2b593a2e5bc79ef3cc88770602e7e569bbd71de113b"
     "0325a6b5eea7e5febae709dab35ec8648908af12cf2d2b569bedc8da0a3a81c1"
     "720838034f1dd3b3da66f6bd4d053ee67c93a747b219d1c546c41c4e425daf93"
     "5a0ddbd75929d24f5ef34944d78789c6c3421aa943c15218bac791c199fc897d"
     default))
 '(package-selected-packages
   '(cape corfu doom-themes evil-collection evil-commentary evil-surround
          evil-textobj-tree-sitter git-gutter gruvbox-theme
          indent-bars markdown-ts-mode nerd-icons-dired org-modern
          queue robot-mode treesit-auto undo-fu vterm xclip))
 '(warning-suppress-types '((treesit))))

(custom-set-faces)

;;; ============================================================
;;; LINE NUMBERS
;;; ============================================================
;; Relative numbers — current line shows 0, others count outward.
;; Makes 5j visible at a glance.
(setq display-line-numbers-type 'relative)
(global-display-line-numbers-mode 1)

;;; ============================================================
;;; THEME
;;; ============================================================

;;; ============================================================
;;; STARTUP UI TWEAKS
;;; ============================================================
(setq inhibit-startup-screen t)

;; (menu-bar-mode -1)        ; uncomment to reclaim the top menu bar's space

(setq scroll-step 1)
(setq scroll-margin 8)      ; keep N lines of context above/below cursor
(add-to-list 'default-frame-alist '(fullscreen . maximized))

;;; ============================================================
;;; SYSTEM CLIPBOARD INTEGRATION
;;; ============================================================
;; Essential for terminal Emacs (shares kill ring with X clipboard);
;; harmless in GUI Emacs.
(use-package xclip
  :config (xclip-mode 1))

;;; ============================================================
;;; EVIL-COMMENTARY — gc operator to toggle comments
;;; ============================================================
;; Examples: gcc (line), gcap (paragraph), gcG (to end of file),
;; gcif (with tree-sitter text objects: inside function).
(use-package evil-commentary
  :ensure t
  :after evil
  :config (evil-commentary-mode 1))

;;; ============================================================
;;; QUALITY-OF-LIFE MODES
;;; ============================================================
(recentf-mode 1)
(save-place-mode 1)              ; remember cursor position per file across sessions
(global-auto-revert-mode 1)

;;; ============================================================
;;; COMPLETION — VERTICAL MINIBUFFER UI
;;; ============================================================
(fido-vertical-mode 1)

;; Make C-n / C-p cycle candidates rather than navigate history.
;; The override has to happen via the minibuffer-setup-hook because
;; evil's state maps (when evil-want-minibuffer is on) shadow the
;; default fido bindings — we install ours buffer-locally inside each
;; new minibuffer to win the precedence race.
(defun my/minibuffer-fido-keys ()
  "Override C-n / C-p in the minibuffer to cycle fido candidates."
  (when (bound-and-true-p icomplete-mode)
    (local-set-key (kbd "C-n") #'icomplete-forward-completions)
    (local-set-key (kbd "C-p") #'icomplete-backward-completions)
    (when (bound-and-true-p evil-local-mode)
      (evil-local-set-key 'normal (kbd "C-n") #'icomplete-forward-completions)
      (evil-local-set-key 'normal (kbd "C-p") #'icomplete-backward-completions)
      (evil-local-set-key 'insert (kbd "C-n") #'icomplete-forward-completions)
      (evil-local-set-key 'insert (kbd "C-p") #'icomplete-backward-completions))))

(add-hook 'minibuffer-setup-hook #'my/minibuffer-fido-keys)

;;; ============================================================
;;; SPELL CHECKING
;;; ============================================================
;; Requires aspell or hunspell installed on the OS.
(add-hook 'org-mode-hook #'flyspell-mode)

;;; ============================================================
;;; PROJECT — smart switch behavior
;;; ============================================================
(require 'project)

;; project.el only knows about projects you've previously visited.
;; This walks ~/Workspace once at startup and registers each git repo
;; so <leader>pp lists them without needing to visit a file first.
(when (file-directory-p "~/Workspace")
  (project-remember-projects-under "~/Workspace"))

(setq project-mode-line t)         ; Emacs 30+ — show project name in mode line

;;; ============================================================
;;; SQL — POSTGRES CONNECTION FROM ENV VARS
;;; ============================================================
;; Connect with M-x sql-connect RET docstore-dev RET.
;; Env vars to set in your shell (~/.bashrc):
;;   DOCSTORE_DB_DEV_USER, _NAME, _HOST, _PORT, _PASSWORD
;;
;; The backtick + ,getenv form is a quasiquote: the list is literal
;; except the parts prefixed with comma, which are evaluated at
;; init-load time. That lets us splice env-var values into a static
;; config structure.
(setq sql-connection-alist
      `((docstore-dev
         (sql-product 'postgres)
         (sql-user     ,(or (getenv "DOCSTORE_DB_DEV_USER") ""))
         (sql-database ,(or (getenv "DOCSTORE_DB_DEV_NAME") ""))
         (sql-server   ,(or (getenv "DOCSTORE_DB_DEV_HOST") ""))
         (sql-password ,(or (getenv "DOCSTORE_DB_DEV_PASSWORD") ""))
         (sql-port     ,(string-to-number
                         (or (getenv "DOCSTORE_DB_DEV_PORT") "5432"))))))

;; Truncate long lines so wide query results stay column-aligned.
(add-hook 'sql-interactive-mode-hook
          (lambda ()
            (toggle-truncate-lines t)))

;;; ============================================================
;;; TREE-SITTER — better syntax highlighting and structural editing
;;; ============================================================
;; Swap *-ts-mode for supported languages and prompt to install
;; missing grammars on demand.
(use-package treesit-auto
  :ensure t
  :demand t
  :config
  (setq treesit-auto-install 'prompt)
  (global-treesit-auto-mode))

;;; ============================================================
;;; TREE-SITTER TEXT OBJECTS FOR EVIL
;;; ============================================================
;; AST-backed text objects: daf, cif, vac, etc.
(use-package evil-textobj-tree-sitter
  :ensure t
  :after evil
  :config
  ;; Function
  (define-key evil-outer-text-objects-map "f"
              (evil-textobj-tree-sitter-get-textobj "function.outer"))
  (define-key evil-inner-text-objects-map "f"
              (evil-textobj-tree-sitter-get-textobj "function.inner"))

  ;; Class
  (define-key evil-outer-text-objects-map "c"
              (evil-textobj-tree-sitter-get-textobj "class.outer"))
  (define-key evil-inner-text-objects-map "c"
              (evil-textobj-tree-sitter-get-textobj "class.inner"))

  ;; Parameter / argument
  (define-key evil-outer-text-objects-map "a"
              (evil-textobj-tree-sitter-get-textobj "parameter.outer"))
  (define-key evil-inner-text-objects-map "a"
              (evil-textobj-tree-sitter-get-textobj "parameter.inner"))

  ;; Comment
  (define-key evil-outer-text-objects-map "C"
              (evil-textobj-tree-sitter-get-textobj "comment.outer"))
  (define-key evil-inner-text-objects-map "C"
              (evil-textobj-tree-sitter-get-textobj "comment.inner")))

;;; ============================================================
;;; TREE-SITTER GRAMMARS — markdown, yaml, toml
;;; ============================================================
;; Markdown is unusual — the repo holds TWO grammars (block + inline)
;; in subdirectories on the split_parser branch, so it needs the
;; 4-element form (LANG URL BRANCH SUBDIR).
(setq treesit-language-source-alist
      '((markdown        "https://github.com/tree-sitter-grammars/tree-sitter-markdown"
                         "split_parser"
                         "tree-sitter-markdown/src")
        (markdown-inline "https://github.com/tree-sitter-grammars/tree-sitter-markdown"
                         "split_parser"
                         "tree-sitter-markdown-inline/src")
        (yaml            "https://github.com/tree-sitter-grammars/tree-sitter-yaml")
        (toml            "https://github.com/tree-sitter-grammars/tree-sitter-toml")))

;; Auto-install missing grammars at startup. First run clones and
;; compiles each (needs a C compiler); subsequent starts are instant.
(dolist (grammar '(markdown markdown-inline yaml toml))
  (unless (treesit-language-available-p grammar)
    (treesit-install-language-grammar grammar)))

(add-to-list 'auto-mode-alist '("\\.md\\'"        . markdown-ts-mode))
(add-to-list 'auto-mode-alist '("\\.markdown\\'"  . markdown-ts-mode))
(add-to-list 'auto-mode-alist '("\\.ya?ml\\'"     . yaml-ts-mode))
(add-to-list 'auto-mode-alist '("\\.toml\\'"      . toml-ts-mode))

(use-package markdown-ts-mode
  :mode ("\\.md\\'" . markdown-ts-mode)
  :defer 't)


;;; ============================================================
;;; GIT GUTTER — show uncommitted changes in the fringe
;;; ============================================================
(use-package git-gutter
  :ensure t
  :config
  (global-git-gutter-mode +1))

;;; ============================================================
;;; AUTO-SAVE ON BUFFER SWITCH
;;; ============================================================
;; Hooks into the lower-level window-buffer-change-functions so it
;; catches every way of leaving a buffer (evil's :b, project switch,
;; mouse clicks, programmatic switches).
(defun my/save-buffer-on-switch ()
  "Save current buffer if it visits a file and has unsaved changes."
  (when (and buffer-file-name
             (buffer-modified-p)
             (file-writable-p buffer-file-name))
    (save-buffer)))

(add-hook 'window-buffer-change-functions
          (lambda (_window) (my/save-buffer-on-switch)))

;;; ============================================================
;;; MISC
;;; ============================================================
;; No beep or flash on C-g, end of buffer, etc.
(setq ring-bell-function 'ignore)


(use-package vterm
  :ensure t)

;;; ============================================================
;;; KEEP PROJECT DIRECTORIES CLEAN
;;; ============================================================
;; Redirect Emacs's sidecar files (foo~, #foo#) into ~/.emacs.d/ so
;; they don't clutter project directories or show up in git status.
;; Lock files (.#foo) can't be relocated — they have to live next to
;; the file they protect — so we just disable them. Safe as long as
;; you don't run multiple Emacs editing the same file simultaneously.
(setq backup-directory-alist
      `(("." . ,(expand-file-name "backups/" user-emacs-directory))))
(setq auto-save-file-name-transforms
      `((".*" ,(expand-file-name "auto-saves/" user-emacs-directory) t)))
(setq create-lockfiles nil)

;;; ============================================================
;;; YAML — use tree-sitter mode automatically
;;; ============================================================
(add-to-list 'auto-mode-alist '("\\.ya?ml\\'" . yaml-ts-mode))

(setq dired-listing-switches "-alh --group-directories-first")

;; Reuse one buffer when navigating into subdirectories. Without
;; this, every RET on a folder opens a new dired buffer and q has
;; to be pressed once per nested folder to clean up.
(setq dired-kill-when-opening-new-dired-buffer t)

(electric-pair-mode 1)

(add-hook 'before-save-hook #'delete-trailing-whitespace)

(setq require-final-newline t)

(setq scroll-conservatively 101)     ; never recenter; smooth incremental scroll

(pixel-scroll-precision-mode 1)

(scroll-bar-mode -1)

(tool-bar-mode -1)

;; In dired, default the destination of copy/move operations to the
;; other dired window when split — fast for "copy A to B" workflows.
(setq dired-dwim-target t)

(defun my/indent-buffer-on-save ()
  "Indent the entire buffer before saving (elisp only)."
  (when (derived-mode-p 'emacs-lisp-mode 'lisp-interaction-mode)
    (indent-region (point-min) (point-max))))

(add-hook 'before-save-hook #'my/indent-buffer-on-save)

(with-eval-after-load 'org
  (setq org-pretty-entities t)
  (setq org-startup-indented t))

;;; ============================================================
;;; COMPLETION — corfu (popup) + cape (sources)
;;; ============================================================
;; corfu: the popup UI. cape: the completion sources that populate it.
;; TAB is left alone — completion auto-triggers as you type; use
;; C-n / C-p inside the popup to navigate and RET to accept.
(use-package corfu
  :ensure t
  :custom
  (corfu-auto t)
  (corfu-auto-delay 0.1)
  (corfu-auto-prefix 1)          ; trigger after 1 char (catches "/")
  (corfu-cycle t)
  (corfu-preselect 'first)
  :init
  (global-corfu-mode))

(use-package cape
  :ensure t
  :init
  ;; Order matters — earlier sources are checked first.
  (add-to-list 'completion-at-point-functions #'cape-file)
  (add-to-list 'completion-at-point-functions #'cape-keyword)
  )

;; :height is in 1/10 pt — 130 = 13pt.
(set-face-attribute 'default nil
                    :family "JetBrains Mono"
                    :height 130)

(set-face-attribute 'variable-pitch nil
                    :family "Iosevka Aile"
                    :height 130)

(use-package doom-themes
  :ensure t
  :config
  )

(load-theme 'modus-vivendi t)

;; First run: M-x nerd-icons-install-fonts to install the font files.
(use-package nerd-icons :ensure t)

(use-package nerd-icons-dired
  :ensure t
  :hook (dired-mode . nerd-icons-dired-mode))

(use-package robot-mode
  :ensure t
  :mode "\\.robot\\'"
  :config
  (evil-define-key '(normal visual) 'global
    (kbd "<leader>r")  #'robot-run-test)    ; run robot test case
  )

;;; ============================================================
;;; INDENT BARS — visible indentation guides for indent-sensitive langs
;;; ============================================================
(use-package indent-bars
  :ensure t
  :hook ((python-mode python-ts-mode yaml-mode yaml-ts-mode) . indent-bars-mode)
  :config
  (setq indent-bars-color '(highlight :face-bg t :blend 0.2)
        indent-bars-pattern "."
        indent-bars-width-frac 0.1))

(use-package org-modern
  :ensure t)
(with-eval-after-load 'org (global-org-modern-mode))


;; Read the test name from the current line, build a robot CLI command,
;; and send it into vterm. Reuses the existing *vterm* buffer if one
;; exists, otherwise creates one (and waits 0.5s for the shell to be
;; ready — otherwise the first character or two can be eaten by a
;; not-yet-initialized terminal).
(defun robot-run-test ()
  (interactive)
  (let* (
	 (testName (string-trim (thing-at-point 'line)))
	 (cmd (format "robot --loglevel TRACE --test '%s' %s\n" testName (buffer-file-name)))
	 )
    (unless (get-buffer "*vterm*")
      (vterm)
      (sit-for 0.5))   ; give the shell half a second to start
    (pop-to-buffer "*vterm*")
    (vterm-send-string cmd)
    )
  )


;;; init.el ends here
