keymap = function(mode, keys, func, desc)
  vim.keymap.set(mode, keys, func, { noremap = true, silent = true, desc = ' ' .. desc })
end

keymap('n', '<C-s>', ':w<CR>', 'Save file')
keymap('n', '<leader>,', '<c-w>5<', 'Resize split left')
keymap('n', '<leader>.', '<c-w>5>', 'Resize split right')
keymap('n', '<Esc>', '<cmd>nohlsearch<CR>', 'Clear highlight')
keymap('n', '<leader>e', ':w | Run<CR>', 'Run program')
keymap('v', '<', '<gv', 'Stay in indent mode')
keymap('v', '>', '>gv', 'Stay in indent mode')
keymap('n', 'n', 'nzz', 'On each search next item stay centered')
keymap('n', 'N', 'Nzz', 'On each search prev item stay centered')
keymap('n', '*', '*zz', 'On jump to next word under cursor stay centered')
keymap('n', '#', '#zz', 'On jump to prev word under cursor stay centered')
keymap('x', 'p', [["_dP]], 'As we paste over something, keep the thing we yanked before')
keymap('n', '<C-f>', ':!tmux neww tmux-sessionizer<CR>', 'New tmux session')
keymap('n', 'x', '"_x', 'x does not override yanked buffer')
keymap('n', 'dd', '"_dd', 'dd to black hole register')
keymap('n', '<leader>b', ':Lexplore<CR>', 'Open netrw')
keymap('n', '<leader>z', ':b#<CR>', 'Go to prev open buffer')
keymap('x', '<leader>e', ':RunCommand<CR>', 'Run the command in buffer')

