live_config_reload = true


[env]
TERM = "xterm-256color"

[font]
size = 8.5

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

