vim.pack.add({"https://github.com/nvim-tree/nvim-web-devicons"})
vim.pack.add({"https://github.com/nvim-lua/plenary.nvim"})

require('core.options')
require('core.commands')
require('core.keymaps')

require('plugins.colorscheme')
require('plugins.treesitter')
require('plugins.treesitter_text')
require('plugins.fzf')
require('plugins.lualine')
require('plugins.lsp')
require('plugins.terminal')
require('plugins.mason_config')
require('plugins.autopair')
require('plugins.blink')
require('plugins.conform_config')
require('plugins.jdtls_config')
require('plugins.fugitive_config')
require('plugins.gitsigns_config')
require('plugins.debug_config')
require('plugins.debug_ui')
require('plugins.yazi_config')
require('plugins.indent')
require('plugins.dadbod_config')
require('plugins.dotenv')



